"LR": 2.5e-4
"NUM_ENVS": 32
"NUM_STEPS": 512
"NUM_STEPS_PER_ENV": 25600
"TOTAL_TIMESTEPS": 3.0e8
"EVAL_FREQ": 1
"NUM_CHECKPOINTS": 4
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.04
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.01
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ANNEAL_LR": True
"LAMBDA_SCHEDULE": False
"LOG_DORMANCY": False
